version: '3.8'

services:
  zephyr-zero-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - ENVIRONMENT=production
      - DATABASE_URL=file:/data/storage.db
      - JWT_SECRET=${JWT_SECRET:-change-this-secret-key}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-change-this-encryption-key-32chars}
      - STORAGE_PATH=/data/uploads
      - AUDIT_LOG_PATH=/data/logs/audit.log
    volumes:
      - ./data:/data
      - ./logs:/data/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis cache service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - zephyr-zero-api
    restart: unless-stopped

volumes:
  redis_data: 